In [117]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [0]:
folder_path = '/content/drive/My Drive/EA_datathon_2020/'
files = ['data_game_launch.csv','data_entitlements.csv','data_session.csv',
         'data_sub.csv','data_games.csv','data_oa_vault.csv',
         'all_trial_users_all_sessions.csv','trial_users_features.csv',
         'all_features.csv',
         'jasper.csv']

In [0]:
all_features_df = pd.read_csv(folder_path+files[8])
label_df = pd.read_csv(folder_path+files[9])

In [121]:
all_features_df.head(5)

user_id  ...  num_unique_games
0  0094a304cf523698c42dae3f57e9c86bfd9bb9a6  ...                 2
1  00f6c95027f5136c3af098b285f1f27cfce8f498  ...                19
2  01191f3dc23f8ec401467c24b943e663c6657089  ...                38
3  011eb817323fc18212156e6c68b0882c407344fd  ...                 2
4  012bd3bfffac2e8cd20c036dd7ee8df9120e9664  ...                23

[5 rows x 24 columns]

In [122]:
label_df.head(5)

user_id  num_days_sub
0  00012443acd80d07693e1269d8854d56e2d50171          1217
1  00014b53a654ad0a6eaa0cc43ce0c03de90356f5           426
2  0007108253314fd345c4cf4f8f9ac0f54396e3b2          1328
3  001100ca786d7dc9c02a21f3aa0882bafb663bce           402
4  001dab7f79dc859b6d07af3a3cb6508a995474bd           373

In [123]:
label_df

user_id  num_days_sub
0     00012443acd80d07693e1269d8854d56e2d50171          1217
1     00014b53a654ad0a6eaa0cc43ce0c03de90356f5           426
2     0007108253314fd345c4cf4f8f9ac0f54396e3b2          1328
3     001100ca786d7dc9c02a21f3aa0882bafb663bce           402
4     001dab7f79dc859b6d07af3a3cb6508a995474bd           373
...                                        ...           ...
9548  ffed27188ad5548d7a66fabe7f8c0f595182f301          1261
9549  fff5c293753b5b05290ea12e2e215a02c2362ad9            34
9550  fffa90b669102f163f0ae3ec18862261cdffe19f           881
9551  fffbdd7dbfcaba8ea0b9b9a80ba2923b5825bd0f            92
9552  fffe062ef33823ca394f424a5a101f4c2da81a11           536

[9553 rows x 2 columns]

In [0]:
merged_df = pd.merge(left=all_features_df, right=label_df, on='user_id')

In [125]:
merged_df.head(5)

user_id  ...  num_days_sub
0  0094a304cf523698c42dae3f57e9c86bfd9bb9a6  ...           245
1  00f6c95027f5136c3af098b285f1f27cfce8f498  ...          1416
2  01191f3dc23f8ec401467c24b943e663c6657089  ...           862
3  011eb817323fc18212156e6c68b0882c407344fd  ...           841
4  012bd3bfffac2e8cd20c036dd7ee8df9120e9664  ...           924

[5 rows x 25 columns]

In [0]:
merged_df2 = merged_df[merged_df['num_days_sub'] < 360]

In [127]:
merged_df2.head(5)

user_id  ...  num_days_sub
0   0094a304cf523698c42dae3f57e9c86bfd9bb9a6  ...           245
5   01a950a01c2f505495d4397b9d36d0b07cc6e0a6  ...            92
14  045e2385aa448bd1e71daf45956ca8985314ab95  ...            61
15  0461a6a2c071e39cea672af51c8902f1d8f97ef9  ...           293
19  0553db12e53a6a30680cdc8cbdf9940534fa2d44  ...           220

[5 rows x 25 columns]

In [0]:
def binarize(val):
  if val < 50:
    return 0
  else:
    return 1

In [129]:
merged_df2['label'] = merged_df2['num_days_sub'].apply(binarize)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [130]:
merged_df2.head(5)

user_id  ...  label
0   0094a304cf523698c42dae3f57e9c86bfd9bb9a6  ...      1
5   01a950a01c2f505495d4397b9d36d0b07cc6e0a6  ...      1
14  045e2385aa448bd1e71daf45956ca8985314ab95  ...      1
15  0461a6a2c071e39cea672af51c8902f1d8f97ef9  ...      1
19  0553db12e53a6a30680cdc8cbdf9940534fa2d44  ...      1

[5 rows x 26 columns]

In [0]:
# def sessions_per_day(row):
#   return int(row['num_sessions_played']) / int(row['num_days_played'])

In [132]:
merged_df2['avg_sessions_per_day'] = merged_df2['num_sessions_played'] / merged_df2['num_days_played']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [133]:
merged_df2.head(5)

user_id  ...  avg_sessions_per_day
0   0094a304cf523698c42dae3f57e9c86bfd9bb9a6  ...              1.000000
5   01a950a01c2f505495d4397b9d36d0b07cc6e0a6  ...              2.700000
14  045e2385aa448bd1e71daf45956ca8985314ab95  ...              1.235294
15  0461a6a2c071e39cea672af51c8902f1d8f97ef9  ...              2.965116
19  0553db12e53a6a30680cdc8cbdf9940534fa2d44  ...              2.642857

[5 rows x 27 columns]

In [0]:
merged_df3=merged_df2.drop(columns=['num_sessions_played','num_days_played'])

In [0]:
merged_df4=merged_df3.sort_values(by='label',ascending=True)

In [136]:
merged_df4

user_id  ...  avg_sessions_per_day
5404  1fc629765ae7c89160787c1372874c41e561e560  ...              2.800000
4035  f2015a4e1a5e14c319ea5a2e12eb6bf651ca210e  ...              1.300000
4041  f3a52bb993d7589049fc7953a6eb61abeef8cd07  ...              2.750000
7457  823ac7e4627daa19856352deb16a8a49ea2b707b  ...              2.000000
7454  7d7334f38c732c427d794c728a99e969af050c38  ...              2.000000
...                                        ...  ...                   ...
4456  d7a5ecb1ccab9764ca86805745f310a6e09989fa  ...              1.888889
4455  d6e8152e45a840c31b7c32275380a7b129fdf128  ...              1.666667
4454  d69be3ab1cb847ea720b13f76b1bb81d95f27f4d  ...              1.255814
4476  e55bed9700782b31629363ccd9872fc464d6d13b  ...              1.083333
9423  eab5bfe68e432b5251d64c89fa181449f7737ee9  ...              1.000000

[5715 rows x 25 columns]

In [0]:
game_titles = ['MASS EFFECT: ANDROMEDA',
 'PLANTS VS ZOMBIES GARDEN WARFARE',
 'PLANTS VS ZOMBIES GARDEN WARFARE 2',
 'SIMCITY (2013)',
 'DEAD SPACE 3',
 'BATTLEFIELD HARDLINE',
 'TITANFALL 2',
 'DRAGON AGE: INQUISITION',
 'MASS EFFECT 1',
 'BATTLEFIELD #3',
 'SIMS 3',
 'CRYSIS 3',
 'BATTLEFRONT',
 'NFS 2016',
 'MASS EFFECT 3',
 'FIFA 16',
 'FIFA 17',
 'BATTLEFIELD 1',
 'SIMS 4',
 'BATTLEFIELD 4']
temp_df = merged_df4.copy()
for title in game_titles:
  temp_df[title] = (temp_df[title] > 0)*1

In [0]:
# temp_df.head(20)

In [205]:
#### final feature list
features_df = temp_df.drop(columns=['avg_sessions_per_day','user_id','label','num_days_sub']).fillna(0)
features_df.tail(5)

MASS EFFECT: ANDROMEDA  ...  num_unique_games
4456                       0  ...                 6
4455                       0  ...                 2
4454                       0  ...                 7
4476                       0  ...                 5
9423                       0  ...                 1

[5 rows x 21 columns]

In [143]:
feature_names = features_df.columns.to_list()
feature_names

['MASS EFFECT: ANDROMEDA',
 'PLANTS VS ZOMBIES GARDEN WARFARE',
 'PLANTS VS ZOMBIES GARDEN WARFARE 2',
 'SIMCITY (2013)',
 'DEAD SPACE 3',
 'BATTLEFIELD HARDLINE',
 'TITANFALL 2',
 'DRAGON AGE: INQUISITION',
 'MASS EFFECT 1',
 'BATTLEFIELD #3',
 'SIMS 3',
 'CRYSIS 3',
 'BATTLEFRONT',
 'NFS 2016',
 'MASS EFFECT 3',
 'FIFA 16',
 'FIFA 17',
 'BATTLEFIELD 1',
 'SIMS 4',
 'BATTLEFIELD 4',
 'num_unique_games',
 'avg_sessions_per_day']

In [206]:
X = np.array(features_df.as_matrix()).astype(float)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [0]:
X[X==np.inf] = 0

In [177]:
np.where(np.isinf(X))

(array([], dtype=int64), array([], dtype=int64))

In [0]:
y=np.array(merged_df4['label'])

In [207]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit(X).transform(X)

In [195]:
X_scaled

array([[-0.19337362, -0.24834582, -0.279097  , ...,  1.581042  ,
        -0.47048855,  1.11497728],
       [-0.19337362, -0.24834582, -0.279097  , ..., -0.63249427,
         0.09881953, -0.50846876],
       [-0.19337362, -0.24834582, -0.279097  , ..., -0.63249427,
         1.2374357 ,  1.06086241],
       ...,
       [-0.19337362, -0.24834582, -0.279097  , ..., -0.63249427,
         0.95278165, -0.55629121],
       [-0.19337362, -0.24834582, -0.279097  , ..., -0.63249427,
         0.38347357, -0.74296653],
       [-0.19337362, -0.24834582, -0.279097  , ..., -0.63249427,
        -0.75514259, -0.83315797]])

In [0]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
from sklearn import svm
cv = ShuffleSplit(n_splits=5, test_size=0.3, random_state=0)
clf1 = LogisticRegression(C=1e5)
clf2 = svm.SVC(kernel='linear', C=1)

In [197]:
X

array([[0.        , 0.        , 0.        , ..., 1.        , 2.        ,
        2.8       ],
       [0.        , 0.        , 0.        , ..., 0.        , 4.        ,
        1.3       ],
       [0.        , 0.        , 0.        , ..., 0.        , 8.        ,
        2.75      ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 7.        ,
        1.25581395],
       [0.        , 0.        , 0.        , ..., 0.        , 5.        ,
        1.08333333],
       [0.        , 0.        , 0.        , ..., 0.        , 1.        ,
        1.        ]])

In [208]:
cross_val_score(clf1, X, y, cv=cv, scoring='f1')

array([0.72498917, 0.70824248, 0.73364289, 0.70942408, 0.72758473])

In [209]:
cross_val_score(clf1, X_scaled, y, cv=cv, scoring='f1')

array([0.73701843, 0.72188317, 0.75051717, 0.72550676, 0.74767932])

In [212]:
clf1.fit(X,y)

LogisticRegression(C=100000.0, class_weight=None, dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [213]:
log_coef = clf1.coef_.flatten().tolist()
log_coef = ['{:.3f}'.format(np.exp(x)) for x in log_coef]
log_coef

['1.575',
 '1.211',
 '0.810',
 '1.005',
 '0.851',
 '1.131',
 '1.056',
 '1.218',
 '1.462',
 '0.972',
 '1.718',
 '1.044',
 '1.127',
 '0.968',
 '1.310',
 '1.562',
 '1.206',
 '1.317',
 '1.632',
 '1.213',
 '1.142']

In [0]:
# q = [': '.join(str(x)) for x in zip(feature_names,log_coef)]

In [0]:
log_coef_sorted, feature_names_sorted  = zip(*sorted(zip(log_coef, feature_names)))

In [215]:
for i in range(0, len(log_coef)):
  print(feature_names_sorted[i] + ': ' + log_coef_sorted[i])

PLANTS VS ZOMBIES GARDEN WARFARE 2: 0.810
DEAD SPACE 3: 0.851
NFS 2016: 0.968
BATTLEFIELD #3: 0.972
SIMCITY (2013): 1.005
CRYSIS 3: 1.044
TITANFALL 2: 1.056
BATTLEFRONT: 1.127
BATTLEFIELD HARDLINE: 1.131
num_unique_games: 1.142
FIFA 17: 1.206
PLANTS VS ZOMBIES GARDEN WARFARE: 1.211
BATTLEFIELD 4: 1.213
DRAGON AGE: INQUISITION: 1.218
MASS EFFECT 3: 1.310
BATTLEFIELD 1: 1.317
MASS EFFECT 1: 1.462
FIFA 16: 1.562
MASS EFFECT: ANDROMEDA: 1.575
SIMS 4: 1.632
SIMS 3: 1.718
